// Single-source design colors for the browser reference and LVGL firmware.
// No packages required. Use --check in CI to detect stale generated files.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, relative } from 'node:path';

const root = resolve(import.meta.dirname, '../..');
const source = 'shared/nav_ui/assets/nav_design_palette.json';
const palette = JSON.parse(readFileSync(resolve(root, source), 'utf8'));
const groups = ['colors', 'ambientMaterial', 'otherPages'];
const tokens = new Set();
for (const group of groups) {
  for (const value of Object.values(palette[group])) {
    if (!/^#[0-9A-F]{6}$/.test(value.hex) || !/^[A-Z_]+$/.test(value.token))
      throw new Error(`Invalid palette entry: ${JSON.stringify(value)}`);
    if (tokens.has(value.token)) throw new Error(`Duplicate palette token: ${value.token}`);
    tokens.add(value.token);
  }
}
const plain = group => Object.fromEntries(Object.entries(palette[group]).map(([key, value]) => [key, value.hex]));
const js = `/* Generated by scripts/preview/build_nav_palette.mjs; edit ${source}. */
(function (root) {
  "use strict";
  const palette = Object.freeze({
    version: ${JSON.stringify(palette.version)},
    colors: Object.freeze(${JSON.stringify(plain('colors'), null, 2)}),
    ambientMaterial: Object.freeze(${JSON.stringify(plain('ambientMaterial'), null, 2)})
  });
  root.NavDesignPalette = palette;
  if (typeof module !== "undefined" && module.exports) module.exports = palette;
})(typeof globalThis !== "undefined" ? globalThis : this);
`;
const entries = groups.flatMap(group => Object.values(palette[group]));
const header = `/* Generated by scripts/preview/build_nav_palette.mjs; edit ${source}. */
#ifndef MOTO_MAP_VISUAL_STYLE_H
#define MOTO_MAP_VISUAL_STYLE_H

// Native round-display colors. The phone's route overview has its own style.
// Ambient tokens prepare the palette; they do not add an ambient renderer.
enum {
    MOTO_MAP_DESIGN_WIDTH = 360,
${entries.map(value => `    MOTO_MAP_${value.token} = 0x${value.hex.slice(1)},`).join('\n')}
    MOTO_MAP_ROUTE_WIDTH = 9,
    MOTO_MAP_ROUTE_SHADOW_WIDTH = 14,
    MOTO_MAP_ROAD_WIDTH = 3,
    MOTO_MAP_ROAD_MAJOR_WIDTH = 4,
    MOTO_MAP_ROAD_MINOR_WIDTH = 2,
    MOTO_MAP_BUILDING_WIDTH = 1,
    MOTO_MAP_FADE_BANDS = 24,
};

#define MOTO_MAP_RED(rgb) (((rgb) >> 16) & 0xFF)
#define MOTO_MAP_GREEN(rgb) (((rgb) >> 8) & 0xFF)
#define MOTO_MAP_BLUE(rgb) ((rgb) & 0xFF)

#endif
`;
for (const [name, content] of [
  ['design/nav-design-palette.js', js],
  ['shared/nav_ui/include/moto_map_visual_style.h', header]
]) {
  const output = resolve(root, name);
  if (process.argv.includes('--check')) {
    const actual = readFileSync(output, 'utf8').replaceAll('\r\n', '\n');
    if (actual !== content) throw new Error(`Stale generated palette: ${relative(root, output)}`);
  } else {
    writeFileSync(output, content, 'utf8');
  }
}
console.log(`Design palette ${process.argv.includes('--check') ? 'verified' : 'generated'}: ${entries.length} colors.`);
