"""Build the small, antialiased 56 px distance font for the 466 px LVGL HUD.

The source font is the repository's Montserrat Bold test font, licensed under
SIL OFL 1.1 in third_party/lvgl/scripts/built_in_font/font_license/Montserrat.
Only the period and digits are embedded in the firmware. Requires Pillow.
"""

from pathlib import Path

from PIL import ImageFont


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "third_party/lvgl/tests/src/test_files/fonts/Montserrat-Bold.ttf"
OUTPUT = ROOT / "shared/nav_ui/assets/moto_font_distance_56.c"
GLYPHS = ".0123456789"
SIZE = 56


def format_bitmap(data: list[int]) -> str:
    return "\n".join(
        "    " + ", ".join(f"0x{value:02x}" for value in data[start : start + 16]) + ","
        for start in range(0, len(data), 16)
    )


def main() -> None:
    font = ImageFont.truetype(str(SOURCE), SIZE)
    bitmap: list[int] = []
    descriptors = [
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},"
    ]
    for character in GLYPHS:
        mask, offset = font.getmask2(character, mode="L", anchor="ls")
        width, height = mask.size
        left, top = offset
        bottom = top + height
        pixels = list(mask)
        start = len(bitmap)
        for index in range(0, len(pixels), 2):
            high = (pixels[index] + 8) // 17
            low = (pixels[index + 1] + 8) // 17 if index + 1 < len(pixels) else 0
            bitmap.append((min(high, 15) << 4) | min(low, 15))
        descriptors.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
            % (start, round(font.getlength(character) * 16), width, height, left, -bottom)
        )

    output = f"""/* Generated by scripts/preview/build_nav_distance_font.py. */
/* Montserrat Bold: SIL OFL 1.1; see third_party/lvgl/scripts/built_in_font/font_license/Montserrat/OFL.txt. */
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include \"lvgl.h\"
#else
#include \"lvgl/lvgl.h\"
#endif

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{format_bitmap(bitmap)}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{chr(10).join(descriptors)}
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{.range_start = 46, .range_length = 1, .glyph_id_start = 1,
      .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
      .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},
    {{.range_start = 48, .range_length = 10, .glyph_id_start = 2,
      .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
      .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t moto_font_distance_56 = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 60,
    .base_line = 10,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -4,
    .underline_thickness = 2,
    .dsc = &font_dsc,
}};
"""
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(bitmap)} bitmap bytes)")


if __name__ == "__main__":
    main()
