// One-time generation of antialiased LVGL A8 masks from the approved SVGs.
// The generated C file is checked in; Sharp is a development dependency only.
// Run from the repository root with `node scripts/preview/build_nav_icon_assets.mjs`.
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const sharp = require('sharp');
const root = resolve(import.meta.dirname, '../..');
const output = resolve(root, 'shared/nav_ui/assets/moto_nav_icons.c');
const names = ['straight', 'left', 'right', 'slight_left', 'slight_right', 'uturn', 'roundabout', 'arrive'];

async function mask(svg, width, height) {
  const { data, info } = await sharp(Buffer.from(svg))
    .resize(width, height, { fit: 'fill' })
    .ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const bytes = [];
  for (let i = 0; i < width * height; i++) bytes.push(data[i * info.channels + info.channels - 1]);
  if (bytes.every((value) => value === 0)) throw new Error('SVG produced an empty alpha mask');
  return bytes;
}

function emit(name, width, height, bytes) {
  const rows = [];
  for (let i = 0; i < bytes.length; i += 16) {
    rows.push('    ' + bytes.slice(i, i + 16).map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ') + ',');
  }
  return `static LV_ATTRIBUTE_MEM_ALIGN const uint8_t ${name}_data[] = {\n${rows.join('\n')}\n};\n` +
    `const lv_image_dsc_t ${name} = {\n` +
    `    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n` +
    `                .w = ${width}, .h = ${height}, .stride = ${width} },\n` +
    `    .data_size = sizeof(${name}_data), .data = ${name}_data,\n` +
    `};\n\n`;
}

let generated = `/* Generated by scripts/preview/build_nav_icon_assets.mjs from design SVG masters. */\n` +
  `#include "moto_nav_icon_assets.h"\n\n`;
for (const name of names) {
  const svg = await readFile(resolve(root, `design/maneuver-icons-v6/${name}.svg`), 'utf8');
  const bytes = await mask(svg.replaceAll('currentColor', '#ffffff'), 64, 64);
  generated += emit(`moto_icon_${name}`, 64, 64, bytes);
}

const vehicle = await readFile(resolve(root, 'design/vehicle-position-marker-v1.svg'), 'utf8');
const paths = [...vehicle.matchAll(/<path d="([^"]+)"[^>]*>/g)];
if (paths.length !== 2) throw new Error('Expected outline and face paths in vehicle marker SVG');
for (const [index, name] of ['moto_marker_outline', 'moto_marker_face'].entries()) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 54" width="48" height="54"><path d="${paths[index][1]}" fill="#ffffff"/></svg>`;
  generated += emit(name, 64, 72, await mask(svg, 64, 72));
}

await writeFile(output, generated.trimEnd() + '\n', 'utf8');
console.log(`Wrote ${output}`);
