"""Build a stationary 64x64 void-and-cluster threshold tile. Not run on MCU."""
from pathlib import Path
import numpy as np

SIZE = 64
count = SIZE * SIZE
random = np.random.default_rng(0x6D6F746F)
mask = np.zeros((SIZE, SIZE), dtype=bool)
mask.flat[random.choice(count, count // 8, replace=False)] = True
axis = np.minimum(np.arange(SIZE), SIZE - np.arange(SIZE))
kernel = np.exp(-(axis[:, None] ** 2 + axis[None, :] ** 2) / (2 * 1.5 ** 2))

def at(index):
    return np.roll(np.roll(kernel, index // SIZE, axis=0), index % SIZE, axis=1)

def cluster(pattern, density):
    return int(np.argmax(np.where(pattern, density, -np.inf)))

def void(pattern, density):
    return int(np.argmin(np.where(pattern, np.inf, density)))

density = np.fft.ifft2(np.fft.fft2(mask) * np.fft.fft2(kernel)).real
for _ in range(count * 8):
    occupied = cluster(mask, density)
    mask.flat[occupied] = False
    density -= at(occupied)
    empty = void(mask, density)
    mask.flat[empty] = True
    density += at(empty)
    if empty == occupied:
        break
else:
    raise RuntimeError("threshold optimization did not converge")

seed_mask, seed_density = mask.copy(), density.copy()
ranks = np.full((SIZE, SIZE), -1, dtype=np.int32)
initial_count = int(mask.sum())
for rank in range(initial_count - 1, -1, -1):
    index = cluster(mask, density)
    ranks.flat[index] = rank
    mask.flat[index] = False
    density -= at(index)
mask, density = seed_mask, seed_density
for rank in range(initial_count, count):
    index = void(mask, density)
    ranks.flat[index] = rank
    mask.flat[index] = True
    density += at(index)

assert np.array_equal(np.sort(ranks.ravel()), np.arange(count))
values = ranks.ravel() >> 4
assert np.all(np.bincount(values) == 16)
lines = ["    " + ",".join(map(str, values[i:i + 32])) + "," for i in range(0, count, 32)]
output = Path("shared/nav_ui/include/moto_nav_dither_tile.hpp")
output.write_text("// Generated by scripts/preview/build_static_dither.py. Fixed screen-space thresholds.\n"
                  "#pragma once\n#include <cstdint>\nnamespace moto::design {\n"
                  "inline constexpr std::uint8_t kDitherTile[4096] = {\n"
                  + "\n".join(lines) + "\n};\n}\n", encoding="utf-8")
print(f"{output}: 4096 values, uniform threshold counts, stationary 64x64 tile")
